---
- hosts: all
  gather_facts: no

  pre_tasks:
      - import_tasks: tasks/ssh_juggle_port.yml

- hosts: all
  become: yes

  roles:
      - role: system
        tags:
            - system

#- name: setting up some security
#  hosts: all
#  roles:
#    - geerlingguy.security
#
      #- name: install docker
      #hosts: all
      #roles:
      #- geerlingguy.docker
