---
- hosts: all
  gather_facts: no

  pre_tasks:
      - import_tasks: tasks/ssh_juggle_port.yml

- hosts: all
  become: yes

  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose

  roles:
      - role: system
        tags:
            - system

      - role: geerlingguy.security
        tags:
            - security

      - role: geerlingguy.docker
        tags:
            - docker

      - role: geerlingguy.pip
        tags:
            - pip

      - role: containers
        tags:
          - containers
