---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: to_be_stored_server_address
      prompt: What is your server ip?
      private: false

    - name: to_be_vaulted_server_root_password
      prompt: What is the root password of the server?
      private: false
    - name: to_be_vaulted_duckdns_email
      prompt: What is your duckdns username (email)?
      private: false
    - name: to_be_vaulted_duckdns_domain_name
      prompt: What is your duckdns domain name?
      private: false
    - name: to_be_vaulted_duckdns_token
      prompt: What is your duckdns token?
      private: false

    - name: vault_password
      prompt: password for encrypting vault-items
      private: false

  vars:
    encrypted_server_root_password: "{{ to_be_vaulted_server_root_password | vault(vault_password, wrap_object=true) | to_yaml }}"
    encrypted_duckdns_email: "{{ to_be_vaulted_duckdns_email | vault(vault_password, wrap_object=true) | to_yaml }}"
    encrypted_duckdns_domain_name: "{{ to_be_vaulted_duckdns_domain_name | vault(vault_password, wrap_object=true) | to_yaml }}"
    encrypted_duckdns_token: "{{ to_be_vaulted_duckdns_token | vault(vault_password, wrap_object=true) | to_yaml }}"

  tasks:
    - name: add host to ssh-config
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        create: true
        block: |
          Host my_server
            HostName {{ to_be_stored_server_address }}

    - name: vault data
      template:
        src: ./group_vars/all/vault.yml.j2
        dest: ./group_vars/all/vault.yml
