---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: to_be_stored_server_address
      prompt: What is your server ip?
      private: false
    - name: to_be_stored_ssh_public_key_path
      prompt: Where is your public ssh-key located?
      private: false
    - name: to_be_stored_server_user
      prompt: What username would you like to have on the server?
      private: false

    - name: to_be_vaulted_server_root_password
      prompt: What is the root password of the server?
      private: false

    - name: to_be_vaulted_duckdns_email
      prompt: What is your duckdns username (email)?
      private: false
    - name: to_be_vaulted_duckdns_domain_name
      prompt: What is your duckdns domain name?
      private: false
    - name: to_be_vaulted_duckdns_token
      prompt: What is your duckdns token?
      private: false

    - name: to_be_vaulted_syncthing_username
      prompt: Type desired username for Syncthing-GUI
      private: false
    - name: to_be_vaulted_syncthing_password
      prompt: Type desired password for Syncthing-GUI
      private: false

    - name: vault_password
      prompt: Type password for encrypting vault-items
      private: false

  vars:
    encrypted_server_root_password: "{{ to_be_vaulted_server_root_password | vault(vault_password, wrap_object=true) | to_yaml }}"
    encrypted_duckdns_email: "{{ to_be_vaulted_duckdns_email | vault(vault_password, wrap_object=true) | to_yaml }}"
    encrypted_duckdns_domain_name: "{{ to_be_vaulted_duckdns_domain_name | vault(vault_password, wrap_object=true) | to_yaml }}"
    encrypted_duckdns_token: "{{ to_be_vaulted_duckdns_token | vault(vault_password, wrap_object=true) | to_yaml }}"
    encrypted_syncthing_username: "{{ to_be_vaulted_syncthing_username | vault(vault_password, wrap_object=true) | to_yaml }}"
    encrypted_syncthing_password: "{{ to_be_vaulted_syncthing_password | vault(vault_password, wrap_object=true) | to_yaml }}"
    pip_install_packages:
      - name: passlib

  tasks:
    - name: add host to ssh-config
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        create: true
        block: |
          Host my_server
            HostName {{ to_be_stored_server_address }}
            Port {{ security_ssh_port }}

    - name: vault data
      template:
        src: ./group_vars/all/vault.yml.j2
        dest: ./group_vars/all/vault.yml

  roles:
    - role: geerlingguy.pip
      tags:
          - pip
