---
- name: SSH Port Juggle | Try connecting
  wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_result

- name: SSH Port Juggle | Set the ansible_port to the fallback default port
  set_fact:
    ansible_ssh_port: "22"
  when:
    - _ssh_port_result is failed

- name: SSH Port Juggle | Try connecting - default port
  wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_default_result
  when:
    - _ssh_port_result is failed

- name: SSH Port Juggle | Set the root credentials
  set_fact:
    ansible_ssh_port: "22"
    ansible_ssh_user: "root"
    ansible_ssh_password: "{{ vault_server_root_password }}"
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is failed

- name: SSH Port Juggle | Try connecting - root
  wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_default_cred_result
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is failed

- name: SSH Port Juggle | Fail
  fail: msg="Neither the configured ansible_port {{ ansible_port }} nor the fallback port 22 were reachable"
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is defined
    - _ssh_port_default_result is failed
    - _ssh_port_root_result is defined
    - _ssh_port_root_result is failed
