#
# SSH (geerlingguy.security)
#
security_ssh_port: 2849
security_sudoers_passwordless: ['{{ username }}']
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "23:00"

#
# Docker and services
#
caddy_name: caddy
vaultwarden_name: vaultwarden
syncthing_name: syncthing

docker_compose_dir: docker_volumes

caddy_dir: "{{ docker_compose_dir}}/{{caddy_name}}"
caddy_config_dir: "{{ docker_compose_dir}}/{{caddy_name}}/config"
caddy_data_dir: "{{ docker_compose_dir}}/{{caddy_name}}/data"

vaultwarden_dir: "{{ docker_compose_dir}}/{{vaultwarden_name}}"
vaultwarden_data_dir: "{{ docker_compose_dir}}/{{vaultwarden_name}}/data"

syncthing_dir: "{{ docker_compose_dir}}/{{syncthing_name}}"
syncthing_config_dir: "{{ docker_compose_dir}}/{{syncthing_name}}/config"

syncthing_vaultwarden_volume_name: volumed-vaultwarden-data
