---
- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}"

- name: copy the compose file
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/docker-compose.yml"

- name: copy Caddyfile
  copy:
    src: templates/Caddyfile # change away from templates
    dest: "{{ docker_compose_dir }}/Caddyfile"

- name: copy caddy.Dockerfile
  copy:
    src: templates/caddy.Dockerfile # change away from templates
    dest: "{{ docker_compose_dir }}/caddy.Dockerfile"

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
